### ISSUE TITLE
评分为 0 时会出现错误

### ISSUE THREAD

**Issue by SunZongming** [WuXiaolong/flutter_movie#2]
当电影没有上映时，评分为 0，会导致进入详情页报错，修改方法：
把 `movie_detail.dart` 中的第 54 行修改为： 
`average: map['rating']['average']==0 ? 0.0 : map['rating']['average'] ,`

**Comment by WuXiaolong** [comment]
多谢反馈

**Comment by xuesongcc** [comment]
@SunZongming 
使用这个项目的时候是不是要重新申请豆瓣的api，我运行后直接一直在跑圆形进度

**Comment by SunZongming** [comment]
@tonyhelloworld  
在 lib/movie/list/movie_list_page.dart 这个文件中，第 69 ~ 72 行我使用的是豆瓣 250 的那个接口 https://api.douban.com/v2/movie/top250?count=100 你可以根据需要去豆瓣官网进行查阅
